### ISSUE TITLE
Rewrite the API doc with apiblueprint

### ISSUE THREAD

**Issue by dakk** [LiskArchive/lisk-docs#19]
A better choice for API documentation could be the apiblueprint format (https://apiblueprint.org/). There are also tools that compile apiblueprint files to HTML (like Aglio).

Example output of apiblueprint + aglio: http://htmlpreview.github.io/?https://raw.githubusercontent.com/danielgtaylor/aglio/blob/master/examples/flatly.html

It's just a thought, I used it for other projects.

**Comment by Isabello** [comment]
This looks great and I would like to redo the API docs in this format.
